/** Offline city → country lookup (no API). Extend freely. */
const CITY_COUNTRY: Record<string, string> = {
  paris: 'France',
  lyon: 'France',
  nice: 'France',
  'new york': 'United States',
  'san francisco': 'United States',
  'los angeles': 'United States',
  chicago: 'United States',
  miami: 'United States',
  seattle: 'United States',
  boston: 'United States',
  washington: 'United States',
  'las vegas': 'United States',
  berlin: 'Germany',
  munich: 'Germany',
  hamburg: 'Germany',
  rome: 'Italy',
  milan: 'Italy',
  venice: 'Italy',
  florence: 'Italy',
  naples: 'Italy',
  'cape town': 'South Africa',
  johannesburg: 'South Africa',
  'rio de janeiro': 'Brazil',
  'sao paulo': 'Brazil',
  london: 'United Kingdom',
  edinburgh: 'United Kingdom',
  manchester: 'United Kingdom',
  dublin: 'Ireland',
  madrid: 'Spain',
  barcelona: 'Spain',
  seville: 'Spain',
  lisbon: 'Portugal',
  porto: 'Portugal',
  amsterdam: 'Netherlands',
  brussels: 'Belgium',
  vienna: 'Austria',
  zurich: 'Switzerland',
  geneva: 'Switzerland',
  prague: 'Czechia',
  budapest: 'Hungary',
  warsaw: 'Poland',
  athens: 'Greece',
  santorini: 'Greece',
  istanbul: 'Türkiye',
  copenhagen: 'Denmark',
  stockholm: 'Sweden',
  oslo: 'Norway',
  helsinki: 'Finland',
  reykjavik: 'Iceland',
  tokyo: 'Japan',
  kyoto: 'Japan',
  osaka: 'Japan',
  seoul: 'South Korea',
  // China — major cities (pinyin)
  beijing: 'China',
  shanghai: 'China',
  'hong kong': 'China',
  guangzhou: 'China',
  canton: 'China',
  shenzhen: 'China',
  chengdu: 'China',
  chongqing: 'China',
  "xi'an": 'China',
  hangzhou: 'China',
  nanjing: 'China',
  wuhan: 'China',
  tianjin: 'China',
  suzhou: 'China',
  qingdao: 'China',
  dalian: 'China',
  shenyang: 'China',
  harbin: 'China',
  kunming: 'China',
  guilin: 'China',
  xiamen: 'China',
  changsha: 'China',
  zhengzhou: 'China',
  jinan: 'China',
  taiyuan: 'China',
  datong: 'China',
  luoyang: 'China',
  lhasa: 'China',
  urumqi: 'China',
  lanzhou: 'China',
  ningbo: 'China',
  wuxi: 'China',
  hefei: 'China',
  fuzhou: 'China',
  nanning: 'China',
  guiyang: 'China',
  macau: 'China',
  macao: 'China',
  // China — provinces & autonomous regions (pinyin)
  shanxi: 'China',
  shaanxi: 'China',
  sichuan: 'China',
  guangdong: 'China',
  yunnan: 'China',
  zhejiang: 'China',
  jiangsu: 'China',
  fujian: 'China',
  hunan: 'China',
  hubei: 'China',
  henan: 'China',
  hebei: 'China',
  shandong: 'China',
  anhui: 'China',
  jiangxi: 'China',
  guizhou: 'China',
  gansu: 'China',
  liaoning: 'China',
  jilin: 'China',
  heilongjiang: 'China',
  hainan: 'China',
  qinghai: 'China',
  xinjiang: 'China',
  tibet: 'China',
  guangxi: 'China',
  ningxia: 'China',
  'inner mongolia': 'China',
  // China — Chinese characters (cities)
  '北京': 'China',
  '上海': 'China',
  '香港': 'China',
  '广州': 'China',
  '深圳': 'China',
  '成都': 'China',
  '重庆': 'China',
  '西安': 'China',
  '杭州': 'China',
  '南京': 'China',
  '武汉': 'China',
  '天津': 'China',
  '苏州': 'China',
  '青岛': 'China',
  '大连': 'China',
  '沈阳': 'China',
  '哈尔滨': 'China',
  '昆明': 'China',
  '桂林': 'China',
  '厦门': 'China',
  '长沙': 'China',
  '郑州': 'China',
  '济南': 'China',
  '太原': 'China',
  '大同': 'China',
  '洛阳': 'China',
  '拉萨': 'China',
  '乌鲁木齐': 'China',
  '兰州': 'China',
  '宁波': 'China',
  '无锡': 'China',
  '合肥': 'China',
  '福州': 'China',
  '南宁': 'China',
  '贵阳': 'China',
  '澳门': 'China',
  // China — Chinese characters (provinces & regions)
  '山西': 'China',
  '陕西': 'China',
  '四川': 'China',
  '广东': 'China',
  '云南': 'China',
  '浙江': 'China',
  '江苏': 'China',
  '福建': 'China',
  '湖南': 'China',
  '湖北': 'China',
  '河南': 'China',
  '河北': 'China',
  '山东': 'China',
  '安徽': 'China',
  '江西': 'China',
  '贵州': 'China',
  '甘肃': 'China',
  '辽宁': 'China',
  '吉林': 'China',
  '黑龙江': 'China',
  '海南': 'China',
  '青海': 'China',
  '新疆': 'China',
  '西藏': 'China',
  '广西': 'China',
  '宁夏': 'China',
  '内蒙古': 'China',
  taipei: 'Taiwan',
  '台北': 'Taiwan',
  bangkok: 'Thailand',
  singapore: 'Singapore',
  'kuala lumpur': 'Malaysia',
  bali: 'Indonesia',
  jakarta: 'Indonesia',
  hanoi: 'Vietnam',
  'ho chi minh city': 'Vietnam',
  delhi: 'India',
  mumbai: 'India',
  dubai: 'United Arab Emirates',
  'abu dhabi': 'United Arab Emirates',
  doha: 'Qatar',
  cairo: 'Egypt',
  marrakesh: 'Morocco',
  marrakech: 'Morocco',
  nairobi: 'Kenya',
  sydney: 'Australia',
  melbourne: 'Australia',
  auckland: 'New Zealand',
  queenstown: 'New Zealand',
  toronto: 'Canada',
  vancouver: 'Canada',
  montreal: 'Canada',
  'mexico city': 'Mexico',
  cancun: 'Mexico',
  'buenos aires': 'Argentina',
  santiago: 'Chile',
  lima: 'Peru',
  cusco: 'Peru',
  bogota: 'Colombia',
}

/** Lowercase and strip spaces/apostrophes/hyphens so "Da Tong" and "Xi'an" match "datong"/"xian". */
const normalize = (s: string) => s.trim().toLowerCase().replace(/[\s'’.\-]+/g, '')

/** Pre-normalized index so lookups are space/punctuation/case-insensitive. */
const NORMALIZED_COUNTRY: Record<string, string> = {}
for (const [city, country] of Object.entries(CITY_COUNTRY)) {
  NORMALIZED_COUNTRY[normalize(city)] = country
}

/** Returns the country for a known city or region, or undefined. Case/space/script-insensitive. */
export function lookupCountry(name: string): string | undefined {
  const key = normalize(name)
  if (!key) return undefined
  return NORMALIZED_COUNTRY[key]
}
